[versions]
gson = "2.11.0"
okhttp = "4.12.0"
ktor = "2.3.12"
log4j = "2.20.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

[bundles]
ktor-server = [
    "ktor-server-core",
    "ktor-server-netty"
]

log4j = [
    "log4j-api",
    "log4j-core",
    "log4j-slf4j-impl",
    "log4j-slf4j2-impl"
]

[plugins]
grgit = { id = "org.ajoberstar.grgit", version = "5.2.2"}
