[versions]
gson = "2.11.0"
okhttp = "4.12.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[bundles]


[plugins]